sbatch extRampLow.sh geneByTissueLow/adrenal_gland.fa      geneByTissue/adrenal_gland.fa
sbatch extRampLow.sh geneByTissueLow/appendix.fa           geneByTissue/appendix.fa
sbatch extRampLow.sh geneByTissueLow/bone_marrow.fa        geneByTissue/bone_marrow.fa
sbatch extRampLow.sh geneByTissueLow/breast.fa             geneByTissue/breast.fa
sbatch extRampLow.sh geneByTissueLow/bronchus.fa           geneByTissue/bronchus.fa
sbatch extRampLow.sh geneByTissueLow/caudate.fa            geneByTissue/caudate.fa
sbatch extRampLow.sh geneByTissueLow/cerebellum.fa         geneByTissue/cerebellum.fa
sbatch extRampLow.sh geneByTissueLow/cerebral_cortex.fa    geneByTissue/cerebral_cortex.fa
sbatch extRampLow.sh geneByTissueLow/cervix_uterine.fa     geneByTissue/cervix_uterine.fa
sbatch extRampLow.sh geneByTissueLow/colon.fa              geneByTissue/colon.fa
sbatch extRampLow.sh geneByTissueLow/duodenum.fa           geneByTissue/duodenum.fa
sbatch extRampLow.sh geneByTissueLow/endometrium_1.fa      geneByTissue/endometrium_1.fa
sbatch extRampLow.sh geneByTissueLow/endometrium_2.fa      geneByTissue/endometrium_2.fa
sbatch extRampLow.sh geneByTissueLow/epididymis.fa         geneByTissue/epididymis.fa
sbatch extRampLow.sh geneByTissueLow/esophagus.fa          geneByTissue/esophagus.fa
sbatch extRampLow.sh geneByTissueLow/fallopian_tube.fa     geneByTissue/fallopian_tube.fa
sbatch extRampLow.sh geneByTissueLow/gallbladder.fa        geneByTissue/gallbladder.fa
sbatch extRampLow.sh geneByTissueLow/heart_muscle.fa       geneByTissue/heart_muscle.fa
sbatch extRampLow.sh geneByTissueLow/hippocampus.fa        geneByTissue/hippocampus.fa
sbatch extRampLow.sh geneByTissueLow/kidney.fa             geneByTissue/kidney.fa
sbatch extRampLow.sh geneByTissueLow/liver.fa              geneByTissue/liver.fa
sbatch extRampLow.sh geneByTissueLow/lung.fa               geneByTissue/lung.fa
sbatch extRampLow.sh geneByTissueLow/lymph_node.fa         geneByTissue/lymph_node.fa
sbatch extRampLow.sh geneByTissueLow/nasopharynx.fa        geneByTissue/nasopharynx.fa
sbatch extRampLow.sh geneByTissueLow/oral_mucosa.fa        geneByTissue/oral_mucosa.fa
sbatch extRampLow.sh geneByTissueLow/pancreas.fa           geneByTissue/pancreas.fa
sbatch extRampLow.sh geneByTissueLow/parathyroid_gland.fa  geneByTissue/parathyroid_gland.fa
sbatch extRampLow.sh geneByTissueLow/placenta.fa           geneByTissue/placenta.fa
sbatch extRampLow.sh geneByTissueLow/prostate.fa           geneByTissue/prostate.fa
sbatch extRampLow.sh geneByTissueLow/rectum.fa             geneByTissue/rectum.fa
sbatch extRampLow.sh geneByTissueLow/salivary_gland.fa     geneByTissue/salivary_gland.fa
sbatch extRampLow.sh geneByTissueLow/seminal_vesicle.fa    geneByTissue/seminal_vesicle.fa
sbatch extRampLow.sh geneByTissueLow/skin_1.fa             geneByTissue/skin_1.fa
sbatch extRampLow.sh geneByTissueLow/skin_2.fa             geneByTissue/skin_2.fa
sbatch extRampLow.sh geneByTissueLow/small_intestine.fa    geneByTissue/small_intestine.fa
sbatch extRampLow.sh geneByTissueLow/soft_tissue_1.fa      geneByTissue/soft_tissue_1.fa
sbatch extRampLow.sh geneByTissueLow/spleen.fa             geneByTissue/spleen.fa
sbatch extRampLow.sh geneByTissueLow/stomach_1.fa          geneByTissue/stomach_1.fa
sbatch extRampLow.sh geneByTissueLow/stomach_2.fa          geneByTissue/stomach_2.fa
sbatch extRampLow.sh geneByTissueLow/testis.fa             geneByTissue/testis.fa
sbatch extRampLow.sh geneByTissueLow/thyroid_gland.fa      geneByTissue/thyroid_gland.fa
sbatch extRampLow.sh geneByTissueLow/tonsil.fa             geneByTissue/tonsil.fa
sbatch extRampLow.sh geneByTissueLow/urinary_bladder.fa    geneByTissue/urinary_bladder.fa
sbatch extRampLow.sh geneByTissueLow/vagina.fa             geneByTissue/vagina.fa
